name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v7

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Build Website
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          bundle exec jekyll build

      - name: Push Website
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          cd _site
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy website to GitHub pages"
          git push --force "https://x-access-token:${DEPLOY_TOKEN}@github.com/openra/openra.github.io.git" master
